### ISSUE TITLE
仿真环境配置

### ISSUE THREAD

**Issue by ZhongLeZhao** [hang0610/Catch_It#1]
你好，我已经按照要求安装，如下：
![image](https://github.com/user-attachments/assets/33dc1a90-f3d6-438c-b384-80da5dad3161)
但是运行这些命令没有反应：
![image](https://github.com/user-attachments/assets/3255bf87-8630-4c99-a14a-6966c36fabc3)
不知是什么原因？是不是需要在安装如下包：
![image](https://github.com/user-attachments/assets/80db56ff-e0b8-4792-b559-f7e594e9ac19)
我只想做个仿真看看效果就行，麻烦抽空可否解答一下，感谢。

**Comment by hang0610** [comment]
Hi Zhongle,

I am not sure what you mean by "运行这些命令没有反应". A screenshot or a detailed bug report would help describe your problem. The packages that you list are all for real-robot deployment so it does no help to solve your simulation problem.

Thanks,
Yuanhang

**Comment by abcd790** [comment]
![image](https://github.com/user-attachments/assets/8b6cef43-e66f-4bd4-a790-36d2f950d5d7)
执行那两个代码后，终端没有任何反馈，也没有出现任何可视化的结果

**Comment by ZhongLeZhao** [comment]
![image](https://github.com/user-attachments/assets/f4601f82-6e13-4f49-9ff3-8bfbf04e6fe7)
执行这两行命令后，在终端没有任何反馈，也没有出现任何可视化界面。

**Comment by hang0610** [comment]
You should replace $(xxx) with the actual value
